import 'package:flutter/material.dart';

import '../../../core/core_ui/core_routes.dart';
import '../../../core/core_ui/models/shared_models.dart';
import '../models/admin_models.dart';
import '../routes/super_admin_routes.dart';

class AdminMockData {
  AdminMockData._();

  static const adminName = 'Basit';
  static const adminRole = 'Super Admin';

  static const navItems = [
    AdminNavItem(
      label: 'Dashboard',
      icon: Icons.grid_view_rounded,
      route: SuperAdminRoutes.dashboard,
    ),
    AdminNavItem(
      label: 'Review Hub',
      icon: Icons.verified_user_rounded,
      route: SuperAdminRoutes.reviewHub,
    ),
    AdminNavItem(
      label: 'Payments',
      icon: Icons.payments_outlined,
      route: SuperAdminRoutes.payments,
    ),
    AdminNavItem(
      label: 'Disputes',
      icon: Icons.gpp_maybe_outlined,
      route: SuperAdminRoutes.disputes,
    ),
    AdminNavItem(
      label: 'Bookings',
      icon: Icons.work_outline_rounded,
      route: SuperAdminRoutes.bookingsMonitor,
    ),
    AdminNavItem(
      label: 'Contracts',
      icon: Icons.article_outlined,
      route: SuperAdminRoutes.contractTemplates,
    ),
    AdminNavItem(
      label: 'Users & Access',
      icon: Icons.groups_2_outlined,
      route: SuperAdminRoutes.users,
    ),
    AdminNavItem(
      label: 'Communications',
      icon: Icons.campaign_outlined,
      route: SuperAdminRoutes.broadcasts,
    ),
    AdminNavItem(
      label: 'Audit Logs',
      icon: Icons.assignment_outlined,
      route: SuperAdminRoutes.auditLogs,
    ),
    AdminNavItem(
      label: 'Analytics',
      icon: Icons.bar_chart_rounded,
      route: SuperAdminRoutes.analytics,
    ),
  ];

  static const kpis = [
    AdminKpi(
      title: 'Pending Verifications',
      value: '42',
      trend: '+9 today',
      sla: '12 older than SLA',
      icon: Icons.verified_user_outlined,
      route: SuperAdminRoutes.verifications,
      tone: AdminDecisionTone.warning,
    ),
    AdminKpi(
      title: 'Pending Payment Proofs',
      value: '18',
      trend: 'PKR 4.2M',
      sla: 'Oldest 23h',
      icon: Icons.payments_outlined,
      route: SuperAdminRoutes.paymentQueue,
      tone: AdminDecisionTone.danger,
    ),
    AdminKpi(
      title: 'Open Disputes',
      value: '7',
      trend: '2 high value',
      sla: '1 safety risk',
      icon: Icons.gpp_maybe_outlined,
      route: SuperAdminRoutes.disputes,
      tone: AdminDecisionTone.danger,
    ),
    AdminKpi(
      title: 'Active Negotiations',
      value: '126',
      trend: '+18%',
      sla: 'Healthy',
      icon: Icons.swap_horiz_rounded,
      route: SuperAdminRoutes.bookingsMonitor,
      tone: AdminDecisionTone.info,
    ),
    AdminKpi(
      title: 'Bookings Secured Today',
      value: '14',
      trend: '+4 vs avg',
      sla: 'Stable',
      icon: Icons.lock_outline_rounded,
      route: SuperAdminRoutes.bookingsMonitor,
      tone: AdminDecisionTone.success,
    ),
    AdminKpi(
      title: 'Revenue This Month',
      value: 'PKR 2.8M',
      trend: '+22%',
      sla: 'On track',
      icon: Icons.show_chart_rounded,
      route: SuperAdminRoutes.analytics,
      tone: AdminDecisionTone.success,
    ),
  ];

  static const feed = [
    AdminFeedItem(
      title: 'Payment proof waiting 5h 20m',
      category: 'Payments',
      age: '5h 20m',
      assignedTo: 'Raamiz',
      priority: 'High',
      route: SuperAdminRoutes.paymentReview,
      risk: AdminRiskTone.high,
    ),
    AdminFeedItem(
      title: 'KYC request older than 24h',
      category: 'KYC',
      age: '28h',
      assignedTo: 'Ayesha',
      priority: 'SLA',
      route: SuperAdminRoutes.verificationDetail,
      risk: AdminRiskTone.medium,
    ),
    AdminFeedItem(
      title: 'High-value dispute needs decision',
      category: 'Dispute',
      age: '2d',
      assignedTo: 'Basit',
      priority: 'Critical',
      route: SuperAdminRoutes.disputeCase,
      risk: AdminRiskTone.critical,
    ),
    AdminFeedItem(
      title: 'Duplicate CNIC risk flag',
      category: 'Trust',
      age: '42m',
      assignedTo: 'Ayesha',
      priority: 'Risk',
      route: SuperAdminRoutes.verificationDetail,
      risk: AdminRiskTone.high,
    ),
    AdminFeedItem(
      title: 'Contract template missing usage rights clause',
      category: 'Legal',
      age: '1d',
      assignedTo: 'Basit',
      priority: 'Medium',
      route: SuperAdminRoutes.contractTemplates,
      risk: AdminRiskTone.medium,
    ),
  ];

  static const kycSubmissions = [
    KycSubmission(
      name: 'Ali Khan',
      role: 'Actor/Talent',
      city: 'Lahore',
      docs: '4/4 docs',
      age: '3h',
      risk: 'No risk',
      assignedTo: 'Ayesha',
      status: 'Pending',
    ),
    KycSubmission(
      name: 'Sara Malik',
      role: 'Location Owner',
      city: 'Karachi',
      docs: '5/5 docs',
      age: '28h',
      risk: 'Address proof mismatch',
      assignedTo: 'Ayesha',
      status: 'SLA risk',
    ),
    KycSubmission(
      name: 'FrameHouse Pvt Ltd',
      role: 'Media Provider',
      city: 'Lahore',
      docs: '6/6 docs',
      age: '11h',
      risk: 'Duplicate device',
      assignedTo: 'Unassigned',
      status: 'Risk flagged',
    ),
    KycSubmission(
      name: 'Nova Brands',
      role: 'Brand/Sponsor',
      city: 'Islamabad',
      docs: '6/6 docs',
      age: '7h',
      risk: 'Bank name mismatch',
      assignedTo: 'Ayesha',
      status: 'Pending',
    ),
  ];

  static const contentItems = [
    AdminContentItem(
      title: 'Fashion campaign portfolio set',
      user: 'Sara Malik',
      role: 'Model',
      type: 'Portfolio Photos',
      time: '32m ago',
      visibility: 'Public pending',
      watermark: 'Passed',
      reports: 0,
      risk: 'Low',
    ),
    AdminContentItem(
      title: 'Image misuse reported by model',
      user: 'Unknown agency',
      role: 'Casting Agency',
      type: 'Reported Content',
      time: '1h ago',
      visibility: 'Hidden while pending',
      watermark: 'Missing',
      reports: 2,
      risk: 'High',
    ),
    AdminContentItem(
      title: 'Rooftop location gallery',
      user: 'Gulberg House',
      role: 'Location Owner',
      type: 'Location Images',
      time: '3h ago',
      visibility: 'Public pending',
      watermark: 'Passed',
      reports: 1,
      risk: 'Medium',
    ),
    AdminContentItem(
      title: 'Drone reel rate claim',
      user: 'FrameHouse Pvt Ltd',
      role: 'Media Provider',
      type: 'Rate Claims',
      time: 'Today',
      visibility: 'Review required',
      watermark: 'N/A',
      reports: 0,
      risk: 'Medium',
    ),
  ];

  static const listings = [
    AdminListing(
      title: 'Gulberg heritage home',
      owner: 'Sara Malik',
      city: 'Lahore',
      category: 'Location',
      price: 'PKR 95k/day',
      deposit: 'PKR 50k',
      date: 'Jul 8',
      visibility: 'Area visible',
      status: 'Pending',
    ),
    AdminListing(
      title: 'ARRI Alexa Mini package',
      owner: 'FrameHouse Pvt Ltd',
      city: 'Karachi',
      category: 'Equipment',
      price: 'PKR 80k/day',
      deposit: 'PKR 120k',
      date: 'Jul 7',
      visibility: 'Provider visible',
      status: 'Pending',
    ),
    AdminListing(
      title: 'DOP + gaffer crew bundle',
      owner: 'Northstar Crew',
      city: 'Islamabad',
      category: 'Services',
      price: 'PKR 180k',
      deposit: 'PKR 35k',
      date: 'Jul 6',
      visibility: 'Public preview',
      status: 'Rejected',
    ),
  ];

  static const bookings = [
    AdminBooking(
      id: 'BK-2048',
      project: 'TVC Shoot - Lahore',
      category: 'Actor',
      parties: 'Hamza / Ali Khan',
      city: 'Lahore',
      value: 'PKR 180,000',
      status: 'Under Negotiation',
      activity: '18m ago',
      risk: 'No risk',
    ),
    AdminBooking(
      id: 'BK-2071',
      project: 'Fashion Campaign - Karachi',
      category: 'Model',
      parties: 'Nova / Sara',
      city: 'Karachi',
      value: 'PKR 350,000',
      status: 'Payment Under Verification',
      activity: '48m ago',
      risk: 'Amount mismatch',
    ),
    AdminBooking(
      id: 'BK-2090',
      project: 'Drama Episode Shoot - Islamabad',
      category: 'Location',
      parties: 'Asad / Gulberg House',
      city: 'Islamabad',
      value: 'PKR 120,000',
      status: 'Disputed',
      activity: '2h ago',
      risk: 'High value',
    ),
  ];

  static const paymentProofs = [
    AdminPaymentProof(
      bookingId: 'BK-2048',
      contractId: 'CC-CON-0041',
      payer: 'Producer: Hamza',
      payee: 'Actor: Ali',
      milestone: 'Deposit',
      expectedAmount: 90000,
      claimedAmount: 90000,
      method: 'Bank Transfer',
      risk: 'No Risk',
      age: '5h',
    ),
    AdminPaymentProof(
      bookingId: 'BK-2052',
      contractId: 'CC-CON-0057',
      payer: 'Brand: Nova',
      payee: 'Model: Sara',
      milestone: 'Final',
      expectedAmount: 250000,
      claimedAmount: 220000,
      method: 'Wallet',
      risk: 'Amount Mismatch',
      age: '18h',
    ),
    AdminPaymentProof(
      bookingId: 'BK-2060',
      contractId: 'CC-CON-0063',
      payer: 'Director: Asad',
      payee: 'Location: Gulberg House',
      milestone: 'Damage Deposit',
      expectedAmount: 50000,
      claimedAmount: 50000,
      method: 'Gateway Ref',
      risk: 'Duplicate Proof',
      age: '27h',
    ),
  ];

  static const disputes = [
    AdminDispute(
      caseId: 'DSP-441',
      type: 'Payment',
      parties: 'Nova vs Sara',
      bookingId: 'BK-2052',
      value: 'PKR 350,000',
      age: '9h',
      assignedTo: 'Basit',
      status: 'Decision Pending',
      severity: 'High',
    ),
    AdminDispute(
      caseId: 'DSP-438',
      type: 'Location Damage',
      parties: 'Asad vs Gulberg House',
      bookingId: 'BK-2090',
      value: 'PKR 120,000',
      age: '1d',
      assignedTo: 'Mahnoor',
      status: 'Evidence Gathering',
      severity: 'Urgent',
    ),
    AdminDispute(
      caseId: 'DSP-432',
      type: 'Harassment / Safety',
      parties: 'Talent report',
      bookingId: 'BK-2012',
      value: 'PKR 95,000',
      age: '2d',
      assignedTo: 'Basit',
      status: 'New',
      severity: 'Safety Risk',
    ),
  ];

  static const users = [
    AdminUserRecord(
      name: 'Ali Khan',
      roles: 'Actor/Talent',
      city: 'Lahore',
      verification: 'Verified',
      trust: 'Contract Ready',
      bookings: 18,
      disputes: 0,
      deviceRisk: 'Clear',
      status: 'Active',
    ),
    AdminUserRecord(
      name: 'Sara Malik',
      roles: 'Model, Location Owner',
      city: 'Karachi',
      verification: 'Pending',
      trust: 'KYC Review',
      bookings: 7,
      disputes: 1,
      deviceRisk: 'Address mismatch',
      status: 'Limited',
    ),
    AdminUserRecord(
      name: 'FrameHouse Pvt Ltd',
      roles: 'Media Provider',
      city: 'Lahore',
      verification: 'Risk flagged',
      trust: 'Duplicate Device',
      bookings: 31,
      disputes: 2,
      deviceRisk: 'Duplicate device',
      status: 'Under review',
    ),
  ];

  static const tickets = [
    AdminTicket(
      id: 'TCK-812',
      source: 'SC-16 report',
      user: 'Sara Malik',
      category: 'Image misuse',
      priority: 'High',
      lastMessage: 'My portfolio was reposted without approval.',
      age: '42m',
      assignedTo: 'Mahnoor',
      status: 'Open',
    ),
    AdminTicket(
      id: 'TCK-807',
      source: 'Payment clarification',
      user: 'Hamza Productions',
      category: 'Payment',
      priority: 'Medium',
      lastMessage: 'Uploaded proof needs clearer transaction ID.',
      age: '5h',
      assignedTo: 'Raamiz',
      status: 'Waiting on User',
    ),
    AdminTicket(
      id: 'TCK-799',
      source: 'KYC follow-up',
      user: 'Gulberg House',
      category: 'Verification',
      priority: 'Normal',
      lastMessage: 'Utility bill uploaded again.',
      age: '1d',
      assignedTo: 'Ayesha',
      status: 'Inbox',
    ),
  ];

  static const auditEvents = [
    AdminAuditEvent(
      timestamp: 'Jul 8, 2026 11:42',
      type: 'Payment approved',
      actor: 'Raamiz',
      affectedUser: 'Hamza Productions',
      entity: 'BK-2048 / CC-CON-0041',
      device: '10.0.2.15 / Admin Mac',
      risk: 'Low',
      description: 'Deposit payment verified and receipts generated.',
      route: SuperAdminRoutes.paymentReview,
    ),
    AdminAuditEvent(
      timestamp: 'Jul 8, 2026 10:18',
      type: 'Verification rejected',
      actor: 'Ayesha',
      affectedUser: 'FrameHouse Pvt Ltd',
      entity: 'KYC-2291',
      device: '10.0.2.18 / Admin Web',
      risk: 'Medium',
      description: 'Duplicate device risk and missing business proof.',
      route: SuperAdminRoutes.verificationDetail,
    ),
    AdminAuditEvent(
      timestamp: 'Jul 7, 2026 19:04',
      type: 'Template published',
      actor: 'Basit',
      affectedUser: 'System',
      entity: 'Model Release v1.1',
      device: '10.0.2.11 / Control Room',
      risk: 'Low',
      description: 'Usage rights clause made mandatory for model contracts.',
      route: SuperAdminRoutes.contractTemplates,
    ),
    AdminAuditEvent(
      timestamp: 'Jul 7, 2026 16:55',
      type: 'User suspended',
      actor: 'Basit',
      affectedUser: 'Unknown agency',
      entity: 'USR-882',
      device: '10.0.2.11 / Control Room',
      risk: 'High',
      description: 'Repeated image misuse reports escalated to support CRM.',
      route: SuperAdminRoutes.users,
    ),
  ];

  static const sharedCoreLinks = [
    ('KYC Upload', CoreRoutes.kyc, Icons.upload_file_outlined),
    (
      'Verification Status',
      CoreRoutes.verificationStatus,
      Icons.fact_check_outlined
    ),
    (
      'Notifications',
      CoreRoutes.notifications,
      Icons.notifications_none_rounded
    ),
    ('Booking Chat', CoreRoutes.chat, Icons.chat_bubble_outline_rounded),
    ('Contract Viewer', CoreRoutes.contract, Icons.description_outlined),
    ('Payment Proof', CoreRoutes.paymentProof, Icons.payments_outlined),
    ('Ledger', CoreRoutes.ledger, Icons.receipt_long_outlined),
    ('Report & Block', CoreRoutes.report, Icons.shield_outlined),
    ('Settings', CoreRoutes.settings, Icons.settings_outlined),
  ];

  static const ledgerEntries = [
    LedgerRowData(
      projectName: 'TVC Shoot - Lahore',
      bookingId: 'BK-2048',
      milestone: 'Deposit',
      amount: 1250000,
      direction: LedgerDirection.incoming,
      status: LedgerStatus.verified,
      date: 'Jul 8, 2026 - 11:32 AM',
      receiptId: 'RCPT-2048-01',
      transactionId: 'HBL-884120',
    ),
    LedgerRowData(
      projectName: 'Fashion Campaign - Karachi',
      bookingId: 'BK-2071',
      milestone: 'Final Payment',
      amount: 350000,
      direction: LedgerDirection.outgoing,
      status: LedgerStatus.released,
      date: 'Jul 7, 2026 - 4:10 PM',
      receiptId: 'RCPT-2071-02',
      transactionId: 'MEZ-119042',
    ),
    LedgerRowData(
      projectName: 'Drama Episode Shoot - Islamabad',
      bookingId: 'BK-2090',
      milestone: 'Damage Deposit',
      amount: 95000,
      direction: LedgerDirection.outgoing,
      status: LedgerStatus.disputed,
      date: 'Jul 6, 2026 - 9:05 AM',
      receiptId: 'RCPT-2090-01',
      transactionId: 'UBL-330187',
    ),
    LedgerRowData(
      projectName: 'Equipment Rental - Karachi',
      bookingId: 'BK-2052',
      milestone: 'Final',
      amount: 220000,
      direction: LedgerDirection.outgoing,
      status: LedgerStatus.refunded,
      date: 'Jul 5, 2026 - 2:44 PM',
      receiptId: 'RCPT-2052-03',
      transactionId: 'HBL-884019',
    ),
  ];

  static const commissionRules = [
    ('Actor bookings', '8%', 'PKR 2,000 min'),
    ('Model campaigns', '10%', 'PKR 3,500 min'),
    ('Location bookings', '7%', 'PKR 4,000 min'),
    ('Equipment rental', '6%', 'PKR 3,000 min'),
    ('Crew services', '8%', 'PKR 2,500 min'),
    ('Brand sponsorship', '12%', 'PKR 8,000 min'),
  ];
}
