#!/usr/bin/env python3
"""Generate a deterministic inventory of interactive Flutter callbacks."""

from __future__ import annotations

import csv
import re
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LIB = ROOT / "lib"
OUTPUT = ROOT / "docs" / "UI_ACTION_INVENTORY.csv"
SUMMARY = ROOT / "docs" / "UI_ACTION_INVENTORY.md"
HANDLER = re.compile(
    r"\b(onPressed|onTap|onLongPress|onChanged|onSubmitted|onDismissed|"
    r"onSelected|onAction|onSave|onDelete|onConfirm|onUpload|onRetry)\s*:"
)


def classify(line: str, context: str) -> str:
    combined = f"{line} {context}".lower()
    if re.search(r"\bon\w+\s*:\s*null\b", line):
        return "disabled"
    if "navigator." in combined or "pushnamed" in combined:
        return "navigation"
    if "setstate" in combined or "controller" in combined:
        return "local_state"
    if any(
        marker in combined
        for marker in (
            "demo",
            "store.",
            "submit",
            "save",
            "delete",
            "remove",
            "approve",
            "reject",
            "upload",
            "publish",
            "send",
            "create",
            "update",
            "toggle",
            "sign",
            "verify",
            "block",
        )
    ):
        return "server_candidate"
    return "review"


def main() -> None:
    rows: list[dict[str, str | int]] = []
    for path in sorted(LIB.rglob("*.dart")):
        lines = path.read_text(encoding="utf-8").splitlines()
        for index, line in enumerate(lines):
            matches = list(HANDLER.finditer(line))
            if not matches:
                continue
            start = max(0, index - 2)
            end = min(len(lines), index + 4)
            context = " ".join(part.strip() for part in lines[start:end])
            for match in matches:
                rows.append(
                    {
                        "file": path.relative_to(ROOT).as_posix(),
                        "line": index + 1,
                        "handler": match.group(1),
                        "classification": classify(line, context),
                        "source": line.strip()[:500],
                    }
                )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8", newline="") as output:
        writer = csv.DictWriter(
            output,
            fieldnames=("file", "line", "handler", "classification", "source"),
        )
        writer.writeheader()
        writer.writerows(rows)

    classifications = Counter(str(row["classification"]) for row in rows)
    handlers = Counter(str(row["handler"]) for row in rows)
    demo_files = sorted(
        path.relative_to(ROOT).as_posix()
        for path in LIB.rglob("*.dart")
        if re.search(
            r"DemoData|DemoStore|shared_mock_data|admin_mock_data",
            path.read_text(encoding="utf-8"),
        )
    )
    summary_lines = [
        "# CineConnect UI Action Inventory",
        "",
        "Generated by `tools/inventory_ui_actions.py`. The CSV is the",
        "line-level source of truth and must be regenerated after Flutter UI changes.",
        "",
        f"- Interactive callback declarations: {len(rows)}",
        f"- Dart files depending on demo/mock data: {len(demo_files)}",
        "",
        "## Callback classification",
        "",
        "| Classification | Count |",
        "|---|---:|",
        *(
            f"| {name} | {count} |"
            for name, count in sorted(classifications.items())
        ),
        "",
        "## Handler types",
        "",
        "| Handler | Count |",
        "|---|---:|",
        *(f"| {name} | {count} |" for name, count in sorted(handlers.items())),
        "",
        "## Migration rule",
        "",
        "Every `server_candidate` row must map to an authenticated API mutation or",
        "be deliberately disabled with an explanation. Navigation and local-state",
        "rows still require review because some callbacks combine navigation with a",
        "demo-store mutation. Completion is checked against the CSV, not only this",
        "summary.",
        "",
        "## Demo/mock consumers",
        "",
        *(f"- `{path}`" for path in demo_files),
        "",
    ]
    SUMMARY.write_text("\n".join(summary_lines), encoding="utf-8")


if __name__ == "__main__":
    main()
