"""insurance policies claims

Revision ID: 0f25fa31c34f
Revises: 81af73d41ffc
Create Date: 2026-07-18 01:44:26.217433

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f25fa31c34f"
down_revision = "81af73d41ffc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insurance_partner_profiles",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("license_number_token", sa.String(length=255), nullable=True),
        sa.Column("coverage_regions", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "insurance_policies",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("booking_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("provider_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("insured_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("coverage_summary", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("document_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("risk_level", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["document_file_id"], ["files.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["insured_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["provider_profile_id"],
            ["insurance_partner_profiles.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "insurance_claims",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("policy_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("booking_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("claimant_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("item_or_room", sa.String(length=180), nullable=True),
        sa.Column("adjuster_user_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("estimate_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adjuster_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["claimant_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["insurance_policies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "insurance_claim_evidence",
        sa.Column("claim_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("caption", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["insurance_claims.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("insurance_claim_evidence")
    op.drop_table("insurance_claims")
    op.drop_table("insurance_policies")
    op.drop_table("insurance_partner_profiles")
    # ### end Alembic commands ###
