"""specialist agency brand model distribution

Revision ID: f32946609750
Revises: f6a7b8c9d0e1
Create Date: 2026-07-17 23:39:19.232350

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f32946609750"
down_revision = "f6a7b8c9d0e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distribution_partner_profiles",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("channels", sa.String(length=255), nullable=True),
        sa.Column("territories", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "brand_profiles",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("representative", sa.String(length=120), nullable=True),
        sa.Column("billing_token", sa.String(length=255), nullable=True),
        sa.Column("trust_status", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["logo_file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "casting_agencies",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("city_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("commission_bps", sa.Integer(), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "distributor_contacts",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("partner_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("channel", sa.String(length=64), nullable=False),
        sa.Column("territory", sa.String(length=120), nullable=True),
        sa.Column("contact_role", sa.String(length=120), nullable=True),
        sa.Column("email_token", sa.String(length=255), nullable=True),
        sa.Column("phone_token", sa.String(length=255), nullable=True),
        sa.Column("prior_project", sa.String(length=180), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["partner_profile_id"],
            ["distribution_partner_profiles.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "model_profiles",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("talent_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("brand_safety_notes", sa.Text(), nullable=True),
        sa.Column("public_visibility", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["talent_profile_id"], ["talent_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("talent_profile_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "agency_invitations",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("agency_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("invited_by", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("talent_user_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("contact_token", sa.String(length=255), nullable=True),
        sa.Column("representation_type", sa.String(length=32), nullable=False),
        sa.Column("commission_bps", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["casting_agencies.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["talent_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "agency_talent",
        sa.Column("agency_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("talent_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("representation_type", sa.String(length=32), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("commission_bps", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["casting_agencies.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["talent_profile_id"], ["talent_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agency_id", "talent_profile_id", name="uq_agency_talent"
        ),
    )
    op.create_table(
        "brand_opportunities",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("brand_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("project_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("budget_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("usage_summary", sa.Text(), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("deliverables", sa.Text(), nullable=True),
        sa.Column("application_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cover_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_profile_id"], ["brand_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["cover_file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "distribution_projects",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("partner_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("release_window_start", sa.Date(), nullable=True),
        sa.Column("release_window_end", sa.Date(), nullable=True),
        sa.Column("territories", sa.String(length=255), nullable=True),
        sa.Column("missing_items", sa.String(length=255), nullable=True),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["partner_profile_id"],
            ["distribution_partner_profiles.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "model_campaign_categories",
        sa.Column("model_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("public_visible", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_profile_id"], ["model_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "model_profile_id", "category", name="uq_model_campaign_category"
        ),
    )
    op.create_table(
        "model_restricted_categories",
        sa.Column("model_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_profile_id"], ["model_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "model_profile_id", "category", name="uq_model_restricted_category"
        ),
    )
    op.create_table(
        "model_usage_rates",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("model_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("scope", sa.String(length=180), nullable=True),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column("negotiable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_profile_id"], ["model_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "model_usage_rights",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("model_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("territory", sa.String(length=120), nullable=False),
        sa.Column("duration_months", sa.Integer(), nullable=True),
        sa.Column("exclusive", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_profile_id"], ["model_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "audition_requests",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("agency_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("project_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("requirement_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("requested_by", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("role_title", sa.String(length=180), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("budget_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["casting_agencies.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["requirement_id"], ["project_requirements.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "brand_applications",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("applicant_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("talent_profile_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("proposal", sa.Text(), nullable=True),
        sa.Column("audience_metrics_json", sa.Text(), nullable=True),
        sa.Column("budget_ask_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["applicant_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["brand_opportunities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["talent_profile_id"], ["talent_profiles.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "distribution_reports",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column(
            "distribution_project_id", sa.Uuid(native_uuid=False), nullable=False
        ),
        sa.Column("partner_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("territory", sa.String(length=120), nullable=False),
        sa.Column("channel", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("audience_count", sa.Integer(), nullable=False),
        sa.Column("revenue_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["distribution_project_id"],
            ["distribution_projects.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["partner_profile_id"],
            ["distribution_partner_profiles.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"], ["files.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "release_handover_items",
        sa.Column(
            "distribution_project_id", sa.Uuid(native_uuid=False), nullable=False
        ),
        sa.Column("label", sa.String(length=180), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["distribution_project_id"],
            ["distribution_projects.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "release_windows",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column(
            "distribution_project_id", sa.Uuid(native_uuid=False), nullable=False
        ),
        sa.Column("channel", sa.String(length=64), nullable=False),
        sa.Column("territory", sa.String(length=120), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("exclusivity", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["distribution_project_id"],
            ["distribution_projects.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "agency_commissions",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("agency_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("booking_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("talent_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("gross_minor", sa.Integer(), nullable=False),
        sa.Column("commission_bps", sa.Integer(), nullable=False),
        sa.Column("commission_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["casting_agencies.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["talent_profile_id"], ["talent_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "audition_candidates",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("audition_request_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("talent_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("agency_note", sa.Text(), nullable=True),
        sa.Column("director_note", sa.Text(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audition_request_id"], ["audition_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["talent_profile_id"], ["talent_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "audition_request_id", "talent_profile_id", name="uq_audition_candidate"
        ),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "brand_terms",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("application_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("exclusivity", sa.String(length=255), nullable=True),
        sa.Column("approval_rights", sa.String(length=255), nullable=True),
        sa.Column("payment_schedule_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["brand_applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "campaign_deliverables",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("booking_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("owner_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("label", sa.String(length=180), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("proof_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["brand_opportunities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["proof_file_id"], ["files.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "campaign_metrics",
        sa.Column("deliverable_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("reach", sa.Integer(), nullable=False),
        sa.Column("engagements", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deliverable_id"], ["campaign_deliverables.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "selection_notes",
        sa.Column("audition_candidate_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("author_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audition_candidate_id"], ["audition_candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "self_tapes",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("audition_candidate_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("thumbnail_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audition_candidate_id"], ["audition_candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["thumbnail_file_id"], ["files.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("self_tapes")
    op.drop_table("selection_notes")
    op.drop_table("campaign_metrics")
    op.drop_table("campaign_deliverables")
    op.drop_table("brand_terms")
    op.drop_table("audition_candidates")
    op.drop_table("agency_commissions")
    op.drop_table("release_windows")
    op.drop_table("release_handover_items")
    op.drop_table("distribution_reports")
    op.drop_table("brand_applications")
    op.drop_table("audition_requests")
    op.drop_table("model_usage_rights")
    op.drop_table("model_usage_rates")
    op.drop_table("model_restricted_categories")
    op.drop_table("model_campaign_categories")
    op.drop_table("distribution_projects")
    op.drop_table("brand_opportunities")
    op.drop_table("agency_talent")
    op.drop_table("agency_invitations")
    op.drop_table("model_profiles")
    op.drop_table("distributor_contacts")
    op.drop_table("casting_agencies")
    op.drop_table("brand_profiles")
    op.drop_table("distribution_partner_profiles")
    # ### end Alembic commands ###
