"""operations safety

Revision ID: f6a7b8c9d0e1
Revises: e5f6a7b8c9d0
Create Date: 2026-07-17 23:20:30.145672

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f6a7b8c9d0e1"
down_revision = "e5f6a7b8c9d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment_provider_profiles",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("provider_type", sa.String(length=64), nullable=False),
        sa.Column("city_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("coverage", sa.String(length=255), nullable=True),
        sa.Column("service_categories", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("rating_average", sa.Integer(), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "location_properties",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("property_type", sa.String(length=64), nullable=False),
        sa.Column("city_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("area_name", sa.String(length=120), nullable=True),
        sa.Column("public_address", sa.String(length=255), nullable=True),
        sa.Column("private_address_token", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("parking_spaces", sa.Integer(), nullable=True),
        sa.Column("power_backup", sa.Boolean(), nullable=False),
        sa.Column("accessible", sa.Boolean(), nullable=False),
        sa.Column("rating_average", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "equipment_items",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("provider_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=True),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("serial_token", sa.String(length=255), nullable=True),
        sa.Column("condition", sa.String(length=64), nullable=False),
        sa.Column("day_rate_minor", sa.Integer(), nullable=True),
        sa.Column("deposit_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("city_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("cover_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["cover_file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["provider_profile_id"],
            ["equipment_provider_profiles.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "equipment_packages",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("provider_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("operator_included", sa.Boolean(), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_profile_id"],
            ["equipment_provider_profiles.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "location_pricing",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("property_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("conditions", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"], ["location_properties.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "location_rules",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("property_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("rule_type", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"], ["location_properties.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "location_spaces",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("property_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("space_type", sa.String(length=64), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("area_sqft", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"], ["location_properties.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "equipment_package_items",
        sa.Column("package_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("equipment_item_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_item_id"], ["equipment_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["equipment_packages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "package_id", "equipment_item_id", name="uq_equipment_package_item"
        ),
    )
    op.create_table(
        "equipment_terms",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("provider_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("equipment_item_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("amount_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("term_type", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_item_id"], ["equipment_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["provider_profile_id"],
            ["equipment_provider_profiles.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "equipment_inspections",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("booking_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("provider_profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("inspection_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("handover_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("return_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed_by_provider", sa.Boolean(), nullable=False),
        sa.Column("signed_by_renter", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["provider_profile_id"],
            ["equipment_provider_profiles.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "incidents",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("booking_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("reported_by", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parties", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("corrective_action", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reported_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "location_inspections",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("booking_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("property_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("inspection_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confirmed_by_owner_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by_renter_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meter_reading", sa.String(length=80), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["property_id"], ["location_properties.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "booking_id", "inspection_type", name="uq_location_booking_inspection"
        ),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "safety_check_ins",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("booking_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latitude_token", sa.String(length=255), nullable=True),
        sa.Column("longitude_token", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "safety_checks",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("booking_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("location_property_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("responsible_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_level", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["location_property_id"], ["location_properties.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["responsible_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "damage_claims",
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("booking_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("claimant_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("respondent_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("inspection_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("claimed_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["claimant_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["inspection_id"], ["location_inspections.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["respondent_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "equipment_inspection_items",
        sa.Column("inspection_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("equipment_item_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("before_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("after_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("accessories_json", sa.Text(), nullable=True),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["after_file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["before_file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["equipment_item_id"], ["equipment_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"], ["equipment_inspections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "location_inspection_items",
        sa.Column("inspection_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("space_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("area_label", sa.String(length=120), nullable=False),
        sa.Column("before_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("after_file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("issue_severity", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["after_file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["before_file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["inspection_id"], ["location_inspections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["location_spaces.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "safety_check_items",
        sa.Column("safety_check_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("label", sa.String(length=180), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["completed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["safety_check_id"], ["safety_checks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "damage_claim_evidence",
        sa.Column("claim_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("file_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("caption", sa.String(length=255), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["damage_claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("damage_claim_evidence")
    op.drop_table("safety_check_items")
    op.drop_table("location_inspection_items")
    op.drop_table("equipment_inspection_items")
    op.drop_table("damage_claims")
    op.drop_table("safety_checks")
    op.drop_table("safety_check_ins")
    op.drop_table("location_inspections")
    op.drop_table("incidents")
    op.drop_table("equipment_inspections")
    op.drop_table("equipment_terms")
    op.drop_table("equipment_package_items")
    op.drop_table("location_spaces")
    op.drop_table("location_rules")
    op.drop_table("location_pricing")
    op.drop_table("equipment_packages")
    op.drop_table("equipment_items")
    op.drop_table("location_properties")
    op.drop_table("equipment_provider_profiles")
    # ### end Alembic commands ###
